BOOTLOADER_BOARD_DIR ?= cores/$(BOARD_PROFILE)/zephyr
BOARD_BOOTLOADER_CONF ?= $(BOOTLOADER_BOARD_DIR)/bootloader.conf
BOARD_BOOTLOADER_OVERLAY ?= $(wildcard $(BOOTLOADER_BOARD_DIR)/bootloader.overlay)
BOOTLOADER_BUILD_DIR ?= $(ZEPHYR_BUILD_ROOT)/$(BOOTLOADER)/$(BOARD_PROFILE)
BOOTLOADER_SHARE_DIR ?= $(ZEPHYR_SHARE_ROOT)/$(BOOTLOADER)/$(BOARD_PROFILE)
BOOTLOADER_BUILD_DIR_DOCKER := $(call docker_path,$(BOOTLOADER_BUILD_DIR))
BOOTLOADER_SHARE_DIR_DOCKER := $(call docker_path,$(BOOTLOADER_SHARE_DIR))
BOOTLOADER_HEX := $(BOOTLOADER_BUILD_DIR)/zephyr/zephyr.hex
RAK3172_BOOTLOADER_BUILD_DIR := $(ZEPHYR_BUILD_ROOT)/$(BOOTLOADER)/rak3172

BOARD_BOOTLOADER_CONF_DOCKER := $(if $(BOARD_BOOTLOADER_CONF),$(DOCKER_WORK)/$(BOARD_BOOTLOADER_CONF),)
BOARD_BOOTLOADER_OVERLAY_DOCKER := $(if $(BOARD_BOOTLOADER_OVERLAY),$(DOCKER_WORK)/$(BOARD_BOOTLOADER_OVERLAY),)

BOOTLOADER_BOARD_ARGS :=
ifneq ($(BOARD_BOOTLOADER_CONF_DOCKER),)
BOOTLOADER_BOARD_ARGS += -DEXTRA_CONF_FILE=$(BOARD_BOOTLOADER_CONF_DOCKER)
endif
ifneq ($(BOARD_BOOTLOADER_OVERLAY_DOCKER),)
BOOTLOADER_BOARD_ARGS += -DDTC_OVERLAY_FILE=$(BOARD_BOOTLOADER_OVERLAY_DOCKER)
endif

.PHONY: bootloader
bootloader: builder.image zephyr.workspace
	@test -n "$(ZEPHYR_BOARD)" || { echo "Unsupported BOARD_PROFILE=$(BOARD_PROFILE)" >&2; exit 1; }
	$(DOCKER_RUN) sh -ec 'west build -b "$(BOARDS)" -d "$(BOOTLOADER_BUILD_DIR_DOCKER)" -p always -s "$(DOCKER_WORK)/$(BOOTLOADER_APP_DIR)/mcuboot/boot/zephyr" -- -DCMAKE_EXPORT_COMPILE_COMMANDS=ON $(BOARD_ROOT_ARG) $(BOOTLOADER_BOARD_ARGS); rm -rf "$(BOOTLOADER_SHARE_DIR_DOCKER)"; mkdir -p "$(BOOTLOADER_SHARE_DIR_DOCKER)"; for f in zephyr.hex zephyr.bin zephyr.elf zephyr.map zephyr.dts .config; do if [ -f "$(BOOTLOADER_BUILD_DIR_DOCKER)/zephyr/$$f" ]; then cp "$(BOOTLOADER_BUILD_DIR_DOCKER)/zephyr/$$f" "$(BOOTLOADER_SHARE_DIR_DOCKER)/$$f"; fi; done; if [ -f "$(BOOTLOADER_BUILD_DIR_DOCKER)/compile_commands.json" ]; then cp "$(BOOTLOADER_BUILD_DIR_DOCKER)/compile_commands.json" "$(BOOTLOADER_SHARE_DIR_DOCKER)/compile_commands.json"; fi; echo "Bootloader artifacts exported: $(BOOTLOADER_SHARE_DIR_DOCKER)"'
