# SPDX-License-Identifier: Apache-2.0

PROFILE_NAME := rak3172t
ZEPHYR_BOARD ?= rak3172
ZEPHYR_BOARD_SOURCE ?= upstream
ZEPHYR_BOARD_VARIANT_OF ?= rak3172
ZEPHYR_SOC ?= stm32wle5cc
JLINK_TARGET ?= STM32WLE5CC
