/*
 * SPDX-License-Identifier: MPL-2.0
 */

#ifndef RUNTIME_ABI_H_
#define RUNTIME_ABI_H_

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define APPLICATION_CTX_APP_BITS     28U
#define APPLICATION_CTX_SYS_NONE     0U
#define APPLICATION_CTX_APP_MASK     ((1UL << APPLICATION_CTX_APP_BITS) - 1UL)
#define APPLICATION_APP_EVT(app_id)  ((uint32_t)(APPLICATION_CTX_SYS_NONE << 28U) | ((uint32_t)(app_id) & APPLICATION_CTX_APP_MASK))
#define APPLICATION_LORAWAN_SEND_HEADER_SIZE        8U
#define APPLICATION_LORAWAN_SEND_PAYLOAD_MAX        24U
#define APPLICATION_DIAGNOSTICS_ADD_PAYLOAD_SIZE    12U
#define APPLICATION_RUNTIME_SERIAL_BEGIN_PAYLOAD_SIZE 12U
#define APPLICATION_BLE_PAIR_PAYLOAD_SIZE           8U
#define APPLICATION_BLE_SET_SECURITY_PAYLOAD_SIZE   12U
#define RTBUS_CLI_LINE_MAX                          256U
#define RTBUS_SERIAL_PORT_0                         0U
#define RTBUS_SERIAL_PORT_1                         1U

enum runtime_gpio_mode {
    RUNTIME_GPIO_MODE_INPUT = 0,
    RUNTIME_GPIO_MODE_OUTPUT,
    RUNTIME_GPIO_MODE_INPUT_PULLUP,
    RUNTIME_GPIO_MODE_INPUT_PULLDOWN,
};

enum rtbus_task_id {
    RTBUS_TASK_DIAGNOSTICS = 0,
    RTBUS_TASK_CLI,
    RTBUS_TASK_RUNTIME_SERIAL,
    RTBUS_TASK_RUNTIME_BLE,
};

enum rtbus_cli_eid {
    RTBUS_CLI_EID_NONE = 0,
    RTBUS_CLI_EID_INPUT,
};

#define RTBUS_CLI_INPUT \
    APPLICATION_APP_EVT(RTBUS_CLI_EID_INPUT)

enum application_runtime_serial_eid {
    APPLICATION_RUNTIME_SERIAL_EID_NONE = 0,
    APPLICATION_RUNTIME_SERIAL_EID_BEGIN,
};

#define APPLICATION_RUNTIME_SERIAL_BEGIN \
    APPLICATION_APP_EVT(APPLICATION_RUNTIME_SERIAL_EID_BEGIN)

enum application_ble_eid {
    APPLICATION_BLE_EID_NONE = 0,
    APPLICATION_BLE_EID_ADV_START,
    APPLICATION_BLE_EID_PAIR,
    APPLICATION_BLE_EID_SET_SECURITY,
};

#define APPLICATION_BLE_ADV_START \
    APPLICATION_APP_EVT(APPLICATION_BLE_EID_ADV_START)
#define APPLICATION_BLE_PAIR \
    APPLICATION_APP_EVT(APPLICATION_BLE_EID_PAIR)
#define APPLICATION_BLE_SET_SECURITY \
    APPLICATION_APP_EVT(APPLICATION_BLE_EID_SET_SECURITY)

#define APPLICATION_LORAWAN_SEND \
    APPLICATION_APP_EVT(APPLICATION_LORAWAN_EID_SEND)

enum application_diagnostics_eid {
    APPLICATION_DIAGNOSTICS_EID_NONE = 0,
    APPLICATION_DIAGNOSTICS_EID_ADD,
    APPLICATION_DIAGNOSTICS_EID_CLI,
};

#define APPLICATION_DIAGNOSTICS_ADD \
    APPLICATION_APP_EVT(APPLICATION_DIAGNOSTICS_EID_ADD)
#define APPLICATION_DIAGNOSTICS_CLI \
    APPLICATION_APP_EVT(APPLICATION_DIAGNOSTICS_EID_CLI)

enum application_dfu_eid {
    APPLICATION_DFU_EID_NONE = 0,
    APPLICATION_DFU_EID_PATCH_STAGED,
    APPLICATION_DFU_EID_APP_STAGED,
    APPLICATION_DFU_EID_CONFIG_STAGED,
    APPLICATION_DFU_EID_CONFIG_STEP_DONE,
    APPLICATION_DFU_EID_IMAGE_STAGED,
};

enum application_dfu_source {
    APPLICATION_DFU_SOURCE_USER = 0,
    APPLICATION_DFU_SOURCE_FUOTA,
};

#define APPLICATION_DFU_PATCH_STAGED \
    APPLICATION_APP_EVT(APPLICATION_DFU_EID_PATCH_STAGED)
#define APPLICATION_DFU_APP_STAGED \
    APPLICATION_APP_EVT(APPLICATION_DFU_EID_APP_STAGED)
#define APPLICATION_DFU_CONFIG_STAGED \
    APPLICATION_APP_EVT(APPLICATION_DFU_EID_CONFIG_STAGED)
#define APPLICATION_DFU_CONFIG_STEP_DONE \
    APPLICATION_APP_EVT(APPLICATION_DFU_EID_CONFIG_STEP_DONE)
#define APPLICATION_DFU_IMAGE_STAGED \
    APPLICATION_APP_EVT(APPLICATION_DFU_EID_IMAGE_STAGED)

struct application_diagnostics_add_req {
    uint32_t result_addr;
    int32_t lhs;
    int32_t rhs;
};

struct application_runtime_serial_begin_req {
    uint32_t result_addr;
    uint32_t port;
    uint32_t baud;
};

struct application_ble_pair_req {
    uint32_t result_addr;
    uint32_t conn;
};

struct application_ble_set_security_req {
    uint32_t result_addr;
    uint32_t conn;
    uint8_t level;
    uint8_t reserved[3];
};

#ifdef __cplusplus
}
#endif

#endif /* RUNTIME_ABI_H_ */
