/*
 * SPDX-License-Identifier: MPL-2.0
 */

#ifndef RUNTIME_ABI_H_
#define RUNTIME_ABI_H_

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define APPLICATION_CTX_APP_BITS     28U
#define APPLICATION_CTX_SYS_NONE     0U
#define APPLICATION_CTX_APP_MASK     ((1UL << APPLICATION_CTX_APP_BITS) - 1UL)
#define APPLICATION_APP_EVT(app_id)  ((uint32_t)(APPLICATION_CTX_SYS_NONE << 28U) | ((uint32_t)(app_id) & APPLICATION_CTX_APP_MASK))
#define APPLICATION_LORAWAN_SEND_HEADER_SIZE        8U
#define APPLICATION_LORAWAN_SEND_PAYLOAD_MAX        24U
#define APPLICATION_DIAGNOSTICS_ADD_PAYLOAD_SIZE    12U
#define APPLICATION_AT_CLI_EXEC_LINE_MAX            256U
#define APPLICATION_BLE_SET_SECURITY_PAYLOAD_SIZE   12U

enum runtime_gpio_mode {
    RUNTIME_GPIO_MODE_INPUT = 0,
    RUNTIME_GPIO_MODE_OUTPUT,
    RUNTIME_GPIO_MODE_INPUT_PULLUP,
    RUNTIME_GPIO_MODE_INPUT_PULLDOWN,
};

enum application_task_id {
    APPLICATION_TASK_DIAGNOSTICS = 0,
    APPLICATION_TASK_AT_CLI,
};

#define APPLICATION_LORAWAN_SEND \
    APPLICATION_APP_EVT(APPLICATION_LORAWAN_EID_SEND)

enum application_at_cli_eid {
    APPLICATION_AT_CLI_EID_NONE = 0,
    APPLICATION_AT_CLI_EID_EXEC_LINE,
};

#define APPLICATION_AT_CLI_EXEC_LINE \
    APPLICATION_APP_EVT(APPLICATION_AT_CLI_EID_EXEC_LINE)

enum application_diagnostics_eid {
    APPLICATION_DIAGNOSTICS_EID_NONE = 0,
    APPLICATION_DIAGNOSTICS_EID_ADD,
};

#define APPLICATION_DIAGNOSTICS_ADD \
    APPLICATION_APP_EVT(APPLICATION_DIAGNOSTICS_EID_ADD)

enum application_dfu_eid {
    APPLICATION_DFU_EID_NONE = 0,
    APPLICATION_DFU_EID_PATCH_STAGED,
    APPLICATION_DFU_EID_APP_STAGED,
    APPLICATION_DFU_EID_CONFIG_STAGED,
    APPLICATION_DFU_EID_CONFIG_STEP_DONE,
    APPLICATION_DFU_EID_IMAGE_STAGED,
};

enum application_dfu_source {
    APPLICATION_DFU_SOURCE_USER = 0,
    APPLICATION_DFU_SOURCE_FUOTA,
};

#define APPLICATION_DFU_PATCH_STAGED \
    APPLICATION_APP_EVT(APPLICATION_DFU_EID_PATCH_STAGED)
#define APPLICATION_DFU_APP_STAGED \
    APPLICATION_APP_EVT(APPLICATION_DFU_EID_APP_STAGED)
#define APPLICATION_DFU_CONFIG_STAGED \
    APPLICATION_APP_EVT(APPLICATION_DFU_EID_CONFIG_STAGED)
#define APPLICATION_DFU_CONFIG_STEP_DONE \
    APPLICATION_APP_EVT(APPLICATION_DFU_EID_CONFIG_STEP_DONE)
#define APPLICATION_DFU_IMAGE_STAGED \
    APPLICATION_APP_EVT(APPLICATION_DFU_EID_IMAGE_STAGED)

struct application_at_cli_exec_line_req {
    uint32_t address;
    uint32_t done_task_id;
    uint32_t done_event_id;
};

struct application_at_cli_exec_line_done_req {
    int32_t status;
};

struct application_diagnostics_add_req {
    uint32_t result_addr;
    int32_t lhs;
    int32_t rhs;
};

#ifdef __cplusplus
}
#endif

#endif /* RUNTIME_ABI_H_ */
