/*
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef RTBUS_NATIVE_SERVICE_NATIVE_ABI_H_
#define RTBUS_NATIVE_SERVICE_NATIVE_ABI_H_

/*
 * Compatibility aliases for the existing native application ABI table.
 *
 * The binary layout and application-facing headers still use the legacy
 * symbols. Keep this private layer so native_service code uses RTBus naming
 * without changing the ABI contract in this step.
 */
#define RTBUS_NATIVE_API_TABLE_BASE          WZ_API_TABLE_BASE
#define RTBUS_NATIVE_API_SLOT_PTR(_slot)     WZ_API_SLOT_PTR(_slot)
#define RTBUS_NATIVE_API_MAGIC               WZ_API_MAGIC
#define RTBUS_NATIVE_API_VERSION             WZ_API_VERSION

#define RTBUS_NATIVE_API_SLOT_MAGIC          WISNODEZ_API_SLOT_MAGIC
#define RTBUS_NATIVE_API_SLOT_VERSION        WISNODEZ_API_SLOT_VERSION
#define RTBUS_NATIVE_API_SLOT_SLOT_COUNT     WISNODEZ_API_SLOT_SLOT_COUNT
#define RTBUS_NATIVE_API_SLOT_RTBUS_POST     WISNODEZ_API_SLOT_RTBUS_POST
#define RTBUS_NATIVE_API_SLOT_DELAY          WISNODEZ_API_SLOT_DELAY
#define RTBUS_NATIVE_API_SLOT_PRINTK         WISNODEZ_API_SLOT_PRINTK
#define RTBUS_NATIVE_API_SLOT_VPRINTK        WISNODEZ_API_SLOT_VPRINTK
#define RTBUS_NATIVE_API_SLOT_RESULT_WAIT    WISNODEZ_API_SLOT_RESULT_WAIT
#define RTBUS_NATIVE_API_SLOT_SERIAL_WRITE   WISNODEZ_API_SLOT_SERIAL_WRITE
#define RTBUS_NATIVE_API_SLOT_GPIO_CONFIGURE WISNODEZ_API_SLOT_GPIO_CONFIGURE
#define RTBUS_NATIVE_API_SLOT_GPIO_WRITE     WISNODEZ_API_SLOT_GPIO_WRITE
#define RTBUS_NATIVE_API_SLOT_GPIO_READ      WISNODEZ_API_SLOT_GPIO_READ
#define RTBUS_NATIVE_API_SLOT_ON_EVENT       WISNODEZ_API_SLOT_ON_EVENT
#define RTBUS_NATIVE_API_SLOT_COUNT          WISNODEZ_API_SLOT_COUNT

#endif /* RTBUS_NATIVE_SERVICE_NATIVE_ABI_H_ */
