BOOTLOADER_BOARD_DIR ?= cores/$(BOARD_PROFILE)/zephyr
BOARD_BOOTLOADER_CONF ?= $(BOOTLOADER_BOARD_DIR)/bootloader.conf
BOARD_BOOTLOADER_OVERLAY ?= $(wildcard $(BOOTLOADER_BOARD_DIR)/bootloader.overlay)
BOOTLOADER_BUILD_DIR ?= cores/$(BOARD_PROFILE)/firmware/build.bootloader
BOOTLOADER_PACKAGE_IMAGE ?= cores/$(BOARD_PROFILE)/firmware/bootloader.hex
BOOTLOADER_BUILD_DIR_DOCKER := $(call docker_path,$(BOOTLOADER_BUILD_DIR))
BOOTLOADER_CONTAINER_BUILD_DIR ?= $(RTBUS_CONTAINER_BUILD_ROOT)/$(BOOTLOADER)/$(BOARD_PROFILE)
BOOTLOADER_HEX := $(BOOTLOADER_BUILD_DIR)/zephyr/zephyr.hex

BOARD_BOOTLOADER_CONF_DOCKER := $(if $(BOARD_BOOTLOADER_CONF),$(DOCKER_WORK)/$(BOARD_BOOTLOADER_CONF),)
BOARD_BOOTLOADER_OVERLAY_DOCKER := $(if $(BOARD_BOOTLOADER_OVERLAY),$(DOCKER_WORK)/$(BOARD_BOOTLOADER_OVERLAY),)

BOOTLOADER_BOARD_ARGS :=
ifneq ($(BOARD_BOOTLOADER_CONF_DOCKER),)
BOOTLOADER_BOARD_ARGS += -DEXTRA_CONF_FILE=$(BOARD_BOOTLOADER_CONF_DOCKER)
endif
ifneq ($(BOARD_BOOTLOADER_OVERLAY_DOCKER),)
BOOTLOADER_BOARD_ARGS += -DDTC_OVERLAY_FILE=$(BOARD_BOOTLOADER_OVERLAY_DOCKER)
endif

.PHONY: bootloader
bootloader: builder.image zephyr.workspace
	@test -n "$(ZEPHYR_BOARD)" || { echo "Unsupported BOARD_PROFILE=$(BOARD_PROFILE)" >&2; exit 1; }
	$(DOCKER_RUN) sh -ec 'rm -rf "$(BOOTLOADER_CONTAINER_BUILD_DIR)" "$(BOOTLOADER_BUILD_DIR_DOCKER)"; cd "$(RTBUS_ZEPHYR_WORKSPACE)" && west build -b "$(BOARDS)" -d "$(BOOTLOADER_CONTAINER_BUILD_DIR)" -s "$(RTBUS_ZEPHYR_WORKSPACE)/$(BOOTLOADER_APP_DIR)/mcuboot/boot/zephyr" -- -DCMAKE_EXPORT_COMPILE_COMMANDS=ON $(BOARD_ROOT_ARG) $(BOOTLOADER_BOARD_ARGS); mkdir -p "$$(dirname "$(BOOTLOADER_BUILD_DIR_DOCKER)")"; cp -a "$(BOOTLOADER_CONTAINER_BUILD_DIR)" "$(BOOTLOADER_BUILD_DIR_DOCKER)"; echo "Bootloader build exported: $(BOOTLOADER_BUILD_DIR_DOCKER)"'

ifneq ($(strip $(BOOTLOADER_PACKAGE_IMAGE)),)
	@test -s "$(BOOTLOADER_BUILD_DIR)/zephyr/zephyr.hex" || { echo "Missing bootloader HEX: $(BOOTLOADER_BUILD_DIR)/zephyr/zephyr.hex" >&2; exit 1; }
	mkdir -p "$(dir $(BOOTLOADER_PACKAGE_IMAGE))"
	cp "$(BOOTLOADER_BUILD_DIR)/zephyr/zephyr.hex" "$(BOOTLOADER_PACKAGE_IMAGE)"
endif
