# RAK3172F has no USB CDC ACM bootloader path. It uses MCUboot scratch swap
# with internal flash slot0 and external SPI NOR slot1.
CONFIG_BOOT_SWAP_USING_SCRATCH=y
CONFIG_BOOT_VALIDATE_SLOT0=y
CONFIG_WISNODEZ_OTA_SHARED_DATA_ADDR=0x2000F400
CONFIG_USB_DEVICE_STACK_NEXT=n
CONFIG_CDC_ACM_SERIAL_INITIALIZE_AT_BOOT=n
CONFIG_BOOT_USB_DFU_NO=y
CONFIG_GPIO=y
CONFIG_GPIO_HOGS=y
CONFIG_SPI=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_SPI_NOR=y
CONFIG_SPI_NOR_FLASH_LAYOUT_PAGE_SIZE=4096
CONFIG_FLASH_JESD216_API=y
