name: Test Local Build

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: false
        persist-credentials: false

    - name: Show runner information
      run: |
        echo "Hello from local runner"
        whoami
        hostname
        uname -a
        pwd
        ls -la
        make board.profile BOARD_PROFILE=rak4631
        make runtime BOARD_PROFILE=rak4631
